# Generated by Django 3.1.2 on 2020-11-21 08:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='origin',
            field=models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=8),
        ),
        migrations.AlterField(
            model_name='virus',
            name='maxPeriod',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='category',
            field=models.CharField(choices=[('Residence', 'Residence'), ('Workplace', 'Workplace'), ('Visit', 'Visit')], max_length=10),
        ),
    ]
