# Generated by Django 3.1.2 on 2020-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20201121_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='origin',
            field=models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=10),
        ),
    ]
