from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
	path('patients',
		views.PatientAllView.as_view(),
		name='patients'),
	path('patient/<int:id>',
		views.PatientShowView.as_view(),
		name='patient-show'),
	path('patient/new',
		views.PatientCreateView.as_view(),
		name='patient-new'),
	path('patient/edit/<int:id>',
		views.PatientEditView.as_view(),
		name='patient-edit'),
	path('patient/delete/<int:id>',
		views.PatientDeleteView.as_view(),
		name='patient-delete'),

	path('viruses',
		views.VirusAllView.as_view(),
		name='viruses'),
	path('virus/<int:id>',
		views.VirusShowView.as_view(),
		name='virus-show'),
	path('virus/new',
		views.VirusCreateView.as_view(),
		name='virus-new'),
	path('virus/edit/<int:id>',
		views.VirusEditView.as_view(),
		name='virus-edit'),
	path('virus/delete/<int:id>',
		views.VirusDeleteView.as_view(),
		name='virus-delete'),

	path('locations',
		views.LocationAllView.as_view(),
		name='locations'),
	path('location/<int:id>',
		views.LocationShowView.as_view(),
		name='location-show'),
	path('location/new',
		views.LocationCreateMainView.as_view(),
		name='location-new'),
	path('location/query',
		views.LocationQueryView.as_view(),
		name='location-query'),
	path('location/create',
		views.LocationCreateView.as_view(),
		name='location-create'),
	path('location/delete/<int:id>',
		views.LocationDeleteView.as_view(),
		name='location-delete'),

	path('cases',
		views.CaseAllView.as_view(),
		name='cases'),
	path('case/<int:id>',
		views.CaseShowView.as_view(),
		name='case-show'),
	path('case/new',
		views.CaseCreateView.as_view(),
		name='case-new'),
	path('case/edit/<int:id>',
		views.CaseEditView.as_view(),
		name='case-edit'),
	path('case/delete/<int:id>',
		views.CaseDeleteView.as_view(),
		name='case-delete'),

	path('<int:case>/visits',
		views.VisitAllView.as_view(),
		name='visits'),
	path('visit/<int:id>',
		views.VisitShowView.as_view(),
		name='visit-show'),
	path('<int:case>/visit/new/',
		views.VisitCreateView.as_view(),
		name='visit-new'),
	path('visit/edit/<int:id>',
		views.VisitEditView.as_view(),
		name='visit-edit'),
	path('visit/delete/<int:id>',
		views.VisitDeleteView.as_view(),
		name='visit-delete'),
]